Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.RetrieveAll.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Logic.RetrieveAll.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.cs, Tarteeb.Api/Services/Foundations/Tickets/ITicketService.cs, Tarteeb.Api/Services/Foundations/Tickets/TicketService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Tickets/TicketService.cs
=> FOUNDATIONS: Retrieve All Tickets

Tarteeb.Api/Controllers/HomeController.cs, Tarteeb.Api/Controllers/TicketsController.cs, Tarteeb.Api/Startup.cs, Tarteeb.Api/Tarteeb.Api.csproj
=> EXPOSERS: Post Ticket

Tarteeb.Api/Controllers/TicketsController.cs
=> EXPOSERS:  GetById Ticket

Tarteeb.Api/Brokers/Storages/StorageBroker.Tickets.cs, Tarteeb.Api/Controllers/TicketsController.cs
=> EXPOSURES: Get All Tickets

Tarteeb.Api/Controllers/UsersController.cs, Tarteeb.Api/Startup.cs
=> EXPOSERS: Post User

Tarteeb.Api/Controllers/UsersController.cs
=> EXPOSERS: Get All Users

Tarteeb.Api/Controllers/UsersController.cs
=> EXPOSER: GetById User

Tarteeb.Api/Controllers/TeamsController.cs, Tarteeb.Api/Startup.cs
=> EXPOSERS: Post Team

Tarteeb.Api/Controllers/TeamsController.cs
=> EXPOSERS: Get Team ById

Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exception.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Logic.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Validations.RemoveById.cs, Tarteeb.Api/Controllers/UsersController.cs, Tarteeb.Api/Services/Foundations/Teams/ITeamService.cs, Tarteeb.Api/Services/Foundations/Teams/TeamService.cs
=> FOUNDATIONS: Remove Team

Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.RemoveById.cs, Tarteeb.Api/Services/Foundations/Users/IUserService.cs, Tarteeb.Api/Services/Foundations/Users/UserService.cs
=> FOUNDATIONS: Remove `User`

Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Logic.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Validations.RemoveById.cs, Tarteeb.Api/Services/Foundations/Tickets/ITicketService.cs, Tarteeb.Api/Services/Foundations/Tickets/TicketService.cs
=> FOUNDATIONS: Remove Ticket

Tarteeb.Api/Controllers/TicketsController.cs
=> EXPOSERS: Delete Ticket

Tarteeb.Api/Controllers/TeamsController.cs
=> EXPOSERS: Get All Teams

Tarteeb.Api/Controllers/UsersController.cs
=> EXPOSERS: Delete User

Tarteeb.Api/Controllers/UsersController.cs
=> EXPOSERS: Put User

Tarteeb.Api/Controllers/TicketsController.cs
=> EXPOSERS: Put Ticket

Tarteeb.Api/Controllers/TeamsController.cs
=> EXPOSERS: Delete Team By Id

Tarteeb.Api/Controllers/TeamsController.cs
=> EXPOSERS: Put Team

Tarteeb.Api/Controllers/TicketsController.cs
=> CODE RUB: Return Inner Exception For Delete Ticket Endpoint

Tarteeb.Api.Tests.Unit/Services/Foundations/Teams/TeamServiceTests.Exceptions.RetrieveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.RetrievebyId.cs
=> CODE RUB: Update Retrieve Team By Id

Tarteeb.Api/Brokers/Storages/StorageBroker.cs
=> CODE RUB: Move place DeleteAsync

Tarteeb.Api/Brokers/Tokens/ITokenBroker.cs, Tarteeb.Api/Brokers/Tokens/TokenBroker.cs, Tarteeb.Api/Models/Tokens/TokenConfiguration.cs, Tarteeb.Api/Startup.cs, Tarteeb.Api/Tarteeb.Api.csproj
=> BROKERS: Create Token Broker And Register It

Tarteeb.Api/Startup.cs, Tarteeb.Api/Tarteeb.Api.csproj
=> CONFIGS: Register Bearer Token And Configurations

Tarteeb.Api/Controllers/AccountsController.cs, Tarteeb.Api/Services/Foundations/Securities/SecurityService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Securities/SecurityService.Validations.cs, Tarteeb.Api/Services/Foundations/Securities/SecurityService.cs, Tarteeb.Api/Startup.cs
=> CONTROLLERS: Login

Tarteeb.Api/Brokers/Storages/IStorageBroker.Times.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Times.cs, Tarteeb.Api/Migrations/20230325095334_AddTimeTable.Designer.cs, Tarteeb.Api/Migrations/20230325095334_AddTimeTable.cs, Tarteeb.Api/Models/Foundations/Times/Time.cs
=> DATA : Model & Migrate `Time`

Tarteeb.Api/Brokers/Storages/IStorageBroker.Times.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Times.cs
=> BROKERS:  Select All `Time`

.gitignore, Tarteeb.Api/Brokers/Storages/IStorageBroker.Scores.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Scores.cs, Tarteeb.Api/Migrations/20230102085421_AddPasswordOnUser.cs, Tarteeb.Api/Migrations/20230210045018_UniqueEmail.cs, Tarteeb.Api/Migrations/20230326160752_CreateScoresTable.Designer.cs, Tarteeb.Api/Migrations/20230326160752_CreateScoresTable.cs, Tarteeb.Api/Models/Foundations/Scores/Score.cs
=> DATA: Model and Migrate `Score`

Tarteeb.Api/Migrations/20230326170440_AddNewColumnsToUser.Designer.cs, Tarteeb.Api/Migrations/20230326170440_AddNewColumnsToUser.cs, Tarteeb.Api/Models/Foundations/Users/User.cs
=> DATA: Added New Fields to User

Tarteeb.Api/Brokers/Storages/IStorageBroker.Scores.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Scores.cs
=> BROKERS: Delete Score

Tarteeb.Api/Brokers/Storages/IStorageBroker.Scores.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Scores.cs
=> BROKERS: Select All Scores

Tarteeb.Api/Brokers/Storages/IStorageBroker.Scores.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Scores.cs
=> BROKERS: `Score` Update

Tarteeb.Api/Brokers/Storages/IStorageBroker.Scores.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Scores.cs
=> BROKERS: `Score` Insert

Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Exceptions.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Logic.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Validations.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/FailedScoreServiceException.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/FailedScoreStorageException.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/InvalidScoreException.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/LockedScoreException.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/NotFoundScoreException.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/ScoreDependencyException.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/ScoreDependencyValidationException.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/ScoreServiceException.cs, Tarteeb.Api/Models/Foundations/Scores/Exceptions/ScoreValidationException.cs, Tarteeb.Api/Services/Foundations/Scores/IScoreService.cs, Tarteeb.Api/Services/Foundations/Scores/ScoreService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Scores/ScoreService.Validations.cs, Tarteeb.Api/Services/Foundations/Scores/ScoreService.cs
=> FOUNDATIONS: Remove Score

Tarteeb.Api/Controllers/ScoresController.cs
=> CONTROLLERS: Delete `Score`

Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Exceptions.Add.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.cs, Tarteeb.Api/Migrations/20230401090436_AddTeamToUser.Designer.cs, Tarteeb.Api/Migrations/20230401090436_AddTeamToUser.cs, Tarteeb.Api/Models/Foundations/Users/User.cs
=> DATA: Update `ManagerId` to `TeamId` And Add Team Property

Tarteeb.Api/Controllers/ScoresController.cs, Tarteeb.Api/Models/Foundations/Times/Time.cs, Tarteeb.Api/Services/Foundations/Scores/IScoreService.cs, Tarteeb.Api/Services/Foundations/Scores/ScoreService.cs
=> CONTROLLERS: Post Score

Tarteeb.Api/Brokers/Storages/StorageBroker.Times.cs, Tarteeb.Api/Controllers/TimesController.cs
=> CONTROLLERS: Post Time

Tarteeb.Api/Controllers/TimesController.cs
=> CONTROLLERS: Delete `Time`

Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Exceptions.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Logic.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Validations.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.ValidationsRetrieveById.cs
=> CODE RUB: Remove . (dot)

Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Exceptions.RetrieveAll.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Logic.RetrieveAll.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.cs, Tarteeb.Api/Services/Foundations/Scores/IScoreService.cs, Tarteeb.Api/Services/Foundations/Scores/ScoreService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Scores/ScoreService.cs
=> FOUNDATIONS: Retrieve All `Scores`

Tarteeb.Api/Controllers/ScoresController.cs
=> CONTROLLERS: Get All Scores

Tarteeb.Api/Controllers/ScoresController.cs, Tarteeb.Api/Controllers/TeamsController.cs
=> CONTROLLERS: Add Forgotten Attribute in `GetAllTeams`

Tarteeb.Api/Controllers/TimesController.cs
=> CONTROLLERS: Put Time

Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.Add.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Tickets/TicketServiceTests.Exceptions.Modify.cs
=> FOUNDATIONS: Verify Ticekt Foreign Keys

Tarteeb.Api.Tests.Unit/Services/Foundations/Emails/EmailServiceTests.Exceptions.Send.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Emails/EmailServiceTests.Logic.Send.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Emails/EmailServiceTests.Validations.Send.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Emails/EmailServiceTests.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Exceptions.Modify.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Logic.Modify.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Validations.Modify.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.cs, Tarteeb.Api/Brokers/Emails/EmailBroker.cs, Tarteeb.Api/Brokers/Emails/IEmailBroker.cs, Tarteeb.Api/Controllers/ScoresController.cs, Tarteeb.Api/Models/Foundations/Emails/Exceptions/EmailDependencyException.cs, Tarteeb.Api/Models/Foundations/Emails/Exceptions/EmailDependencyValidationException.cs, Tarteeb.Api/Models/Foundations/Emails/Exceptions/EmailServiceException.cs, Tarteeb.Api/Models/Foundations/Emails/Exceptions/EmailValidationException.cs, Tarteeb.Api/Models/Foundations/Emails/Exceptions/FailedEmailServerException.cs, Tarteeb.Api/Models/Foundations/Emails/Exceptions/FailedEmailServiceException.cs, Tarteeb.Api/Models/Foundations/Emails/Exceptions/InvalidEmailException.cs, Tarteeb.Api/Models/Foundations/Emails/Exceptions/NullEmailException.cs, Tarteeb.Api/Services/Foundations/Emails/EmailService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Emails/EmailService.Validations.cs, Tarteeb.Api/Services/Foundations/Emails/EmailService.cs, Tarteeb.Api/Services/Foundations/Emails/IEmailService.cs, Tarteeb.Api/Services/Foundations/Scores/ScoreService.Validations.cs, Tarteeb.Api/Startup.cs, Tarteeb.Api/Tarteeb.Api.csproj, Tarteeb.Api/libman.json
=> FOUNDATIONS: Send Email

Tarteeb.Api/Controllers/AccountsController.cs
=> CONTROLLERS: Sign UP

Tarteeb.Api/Migrations/20230402145941_UpdateToBoolean.Designer.cs, Tarteeb.Api/Migrations/20230402145941_UpdateToBoolean.cs, Tarteeb.Api/Models/Foundations/Users/User.cs
=> DATA: Update Flags To Boolean Type

Tarteeb.Api.Tests.Unit/Services/Foundations/Scores/ScoreServiceTests.Exceptions.Modify.cs, Tarteeb.Api/Services/Foundations/Scores/ScoreService.Validations.cs
=> CODE RUB : Remove EffortLink Validation Rule

.gitignore, Tarteeb.Api/Brokers/Storages/StorageBroker.Milestones.cs, Tarteeb.Api/Migrations/20230416132531_CreatedMilestoneTable.Designer.cs, Tarteeb.Api/Migrations/20230416132531_CreatedMilestoneTable.cs, Tarteeb.Api/Migrations/20230416184234_AddedUserFieldToMilestone.Designer.cs, Tarteeb.Api/Migrations/20230416184234_AddedUserFieldToMilestone.cs, Tarteeb.Api/Models/Foundations/Milestones/Milestone.cs
=> DATA: Model & Migrate `Milestone`

Tarteeb.Api/Brokers/Storages/IStorageBroker.Milestones.cs
=> BROKERS: Select All `Milestone`

Tarteeb.Api/Brokers/Storages/IStorageBroker.Milestones.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Milestones.cs
=> BROKERS: Update `Milestone`

Tarteeb.Api/Brokers/Storages/IStorageBroker.Milestones.cs
=> BROKERS : Insert `Milestone`

Tarteeb.Api/Brokers/Storages/IStorageBroker.Milestones.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Milestones.cs
=> BROKERS : Delete `Milestone`

Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.Exceptions.Add.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.Logic.Add.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.Validations.Add.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/AlreadyExistsMilestoneException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/FailedMilestoneServiceException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/FailedMilestoneStorageException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/InvalidMilestoneException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/InvalidMilestoneReferenceException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/LockedMilestoneException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/MilestoneDependencyException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/MilestoneDependencyValidationException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/MilestoneServiceException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/MilestoneValidationException.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/NullMilestoneException.cs, Tarteeb.Api/Services/Foundations/Milestones/IMilestoneService.cs, Tarteeb.Api/Services/Foundations/Milestones/MilestoneService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Milestones/MilestoneService.Validations.cs, Tarteeb.Api/Services/Foundations/Milestones/MilestoneService.cs
=> FOUNDATIONS : Add `Milestone`

Tarteeb.Api/Migrations/20230419052127_ChangeProperytNameMilestoneTable.Designer.cs, Tarteeb.Api/Migrations/20230419052127_ChangeProperytNameMilestoneTable.cs, Tarteeb.Api/Models/Foundations/Milestones/Milestone.cs
=> CODE RUB : Fix Discription in Milestone Class To Description

Tarteeb.Api/Brokers/Storages/IStorageBroker.Milestones.cs, Tarteeb.Api/Brokers/Storages/StorageBroker.Milestones.cs
=> BROKERS : Select `Milestone` ById

Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.Exceptions.RetrieveAll.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.Logic.RetrieveAll.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.cs, Tarteeb.Api/Services/Foundations/Milestones/IMilestoneService.cs, Tarteeb.Api/Services/Foundations/Milestones/MilestoneService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Milestones/MilestoneService.cs
=> FOUNDATIONS : Retrieve All Milestone

Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.Exceptions.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.Logic.RemoveById.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Milestones/MilestoneServiceTests.Validations.RemoveById.cs, Tarteeb.Api/Models/Foundations/Milestones/Exceptions/NotFoundMilestoneException.cs, Tarteeb.Api/Services/Foundations/Milestones/IMilestoneService.cs, Tarteeb.Api/Services/Foundations/Milestones/MilestoneService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Milestones/MilestoneService.Validations.cs, Tarteeb.Api/Services/Foundations/Milestones/MilestoneService.cs
=> FOUNDATIONS: Remove `Milestone`

Tarteeb.Api/Controllers/MilestonesController.cs
=> CONTROLLERS: Post `Milestone`

Tarteeb.Api/Controllers/MilestonesController.cs
=> CONTROLLERS: Put `Milestone`

.gitignore, Tarteeb.Api/Controllers/MilestonesController.cs
=> CONTROLLERS : Get All `Milestone`

Tarteeb.Api/Controllers/MilestonesController.cs
=> CODE RUB: Added InvalidMilestoneReferenceException in `Milestone` controller

Tarteeb.Api/Controllers/MilestonesController.cs
=> CONTROLLERS : Delete `Milestone`

Tarteeb.Api/Startup.cs
=> CODE RUB : Add Support For Login In Swagger

Tarteeb.Api/Brokers/Tokens/ITokenBroker.cs, Tarteeb.Api/Brokers/Tokens/TokenBroker.cs
=> BROKERS :  Add HashToken

Tarteeb.Api/Controllers/AccountsController.cs
=> CODE RUB : Change AccountController From BadGateway TO BadRequest

Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.Logic.Create.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.Logic.Hash.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.Validations.Create.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.Validations.Hash.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Securities/SecurityServiceTests.cs, Tarteeb.Api/Models/Foundations/Securities/Exceptions/InsecurePasswordException.cs, Tarteeb.Api/Services/Foundations/Securities/ISecurityService.cs, Tarteeb.Api/Services/Foundations/Securities/SecurityService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Securities/SecurityService.Validations.cs, Tarteeb.Api/Services/Foundations/Securities/SecurityService.cs
=> FOUNDATIONS: Hash Password

Tarteeb.Api/Brokers/Storages/StorageBroker.Users.cs
=> CODE RUB: Remove Empty Lines

Tarteeb.Api.Tests.Unit/Services/Orchestrations/UserSecurityOrchestrationServiceTests.Logic.CreateToken.cs, Tarteeb.Api.Tests.Unit/Services/Orchestrations/UserSecurityOrchestrationServiceTests.Validations.CreateToken.cs, Tarteeb.Api/Services/Orchestrations/UserSecurities/UserSecurityOrchestrationService.Validations.cs, Tarteeb.Api/Services/Orchestrations/UserSecurities/UserSecurityOrchestrationService.cs
=> ORCHESTRATIONS: Add Logic While Login

Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Logic.Add.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.Add.cs, Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.cs, Tarteeb.Api/Services/Foundations/Users/UserService.Exceptions.cs, Tarteeb.Api/Services/Foundations/Users/UserService.Validations.cs
=> FOUNDATIONS: Add Email Validation in UserService.cs

Tarteeb.Api/Migrations/20230709131640_CreateDateWorkedColumnToTimeTable.Designer.cs, Tarteeb.Api/Migrations/20230709131640_CreateDateWorkedColumnToTimeTable.cs, Tarteeb.Api/Models/Foundations/Times/Time.cs
=> DATA: Upgrade `Time`

Tarteeb.Api.Tests.Unit/Services/Processings/Users/UserProcessingsServiceTests.Exceptions.VerifyById.cs, Tarteeb.Api.Tests.Unit/Services/Processings/Users/UserProcessingsServiceTests.Logic.VerifyById.cs, Tarteeb.Api.Tests.Unit/Services/Processings/Users/UserProcessingsServiceTests.cs, Tarteeb.Api/Models/Processings/Users/Exeptions/UserProcessingDependencyValidationException.cs, Tarteeb.Api/Models/Processings/Users/FailedUserProcessingServiceException.cs, Tarteeb.Api/Models/Processings/Users/UserProcessingDependencyValidationException.cs, Tarteeb.Api/Models/Processings/Users/UserProcessingServiceException.cs, Tarteeb.Api/Services/Processings/Users/UserProcessingService.Exceptions.cs, Tarteeb.Api/Services/Processings/Users/UserProcessingService.cs
=> PROCESSINGS: Verify User

Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Exceptions.RetrieveAll.cs, Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Logic.RetrieveAll.cs, Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.cs
=> PROCESSINGS: Retrieve All User Profiles

Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Exceptions.Modify.cs, Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Exceptions.RetrieveById.cs, Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Logic.Modify.cs, Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Logic.RetrieveById.cs, Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Validation.Modify.cs, Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Validations.RetrieveById.cs, Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.cs, Tarteeb.Api/Models/Processings/UserProfiles/Exceptions/NullUserProfileProcessingException.cs, Tarteeb.Api/Services/Processings/UserProfiles/IUserProfileProcessingService.cs, Tarteeb.Api/Services/Processings/UserProfiles/UserProfileProcessingService.Exceptions.cs, Tarteeb.Api/Services/Processings/UserProfiles/UserProfileProcessingService.Validations.cs, Tarteeb.Api/Services/Processings/UserProfiles/UserProfileProcessingService.cs
=> PROCESSINGS: Modify User Profile

Tarteeb.Api.Tests.Unit/Services/Processings/UserProfiles/UserProfileProcessingServiceTests.Validations.RetrieveById.cs, Tarteeb.Api/Controllers/UserProfilesController.cs
=> CONTROLLERS: Put User Profile

Tarteeb.Api/Controllers/UsersController.cs, Tarteeb.Api/Services/Processings/Users/UserProcessingService.Exceptions.cs
=> CONTROLLERS: Verify User By Id

Tarteeb.Api/Controllers/UserProfilesController.cs, Tarteeb.Api/Models/Foundations/Users/Exceptions/NotFoundUserException.cs, Tarteeb.Api/Models/Processings/UserProfiles/Exceptions/UserProfileProcessingDependencyValidationException.cs, Tarteeb.Api/Services/Processings/UserProfiles/UserProfileProcessingService.cs
=> MEDIUM FIX: Troubleshoot Not Found Use-Case

Tarteeb.Api.Tests.Unit/Services/Foundations/Users/UserServiceTests.Validations.Add.cs
=> CODE RUB: Remove ?
